### ISSUE TITLE
URL misinterpretation

### ISSUE THREAD

**Issue by JvandeKraats** [hayageek/WhatsApp-Web#1]
Today, when a friend of mine send me this link in whatsapp: '**Zoom.us**', it redirected me to: '**https://web.whatsapp.com/Zoom.us**' instead of the normal '**Zoom.us**' when using the web.whatsapp version of whatsapp. When i used my phone to open the link it forwarded me to the right URL.

**Comment by hayageek** [comment]
invalid bug.
